### PR TITLE
docs: Mention bear for indexing Make-based projects

### PR DESCRIPTION
**Pull request by varungandhi-src**

### CODE REVIEW

**Comment by i-ky** [comment]
Maybe you can just add a link to [compilation database format description](https://clang.llvm.org/docs/JSONCompilationDatabase.html)? It mentions CMake, Bazel and Bear, it may list more (because there are more) alternatives in the future.

**Comment by varungandhi-src** [comment]
There is already a link to that reference earlier in the docs. The reason for mentioning Bear here is that it reduces the number of indirections (you don't need to go the Clang docs, then identify that Bear might work for you, then figure out how to use Bear).

**Comment by i-ky** [comment]
> There is already a link to that reference earlier in the docs.

It is mentioned in the context of what compilation database is, but the link may be helpful is the context of compilation database generation as well.

> The reason for mentioning Bear here is that it reduces the number of indirections (you don't need to go the Clang docs, then identify that Bear might work for you, then figure out how to use Bear).

I understand the intentions. The problem is that Bear might _not_ work, which leaves user in a dead end with no alternative solutions in sight.

**Comment by i-ky** [comment]
Correct.

**Comment by varungandhi-src** [comment]
I suppose that's unlikely, but there's no harm in addiing a second mention. I've opened https://github.com/sourcegraph/scip-clang/pull/385 for that.

**Comment by i-ky** [comment]
I thought it was unlikely too, but then I ended up working on a project which defeated Bear and ended up writing [my own generator](https://github.com/i-ky/basset) :rofl:

**Comment by varungandhi-src** [comment]
Would you like me to mention your tool in the README, or would you rather not have the extra attention (e.g. someone may file an issue etc.)?

> but then I ended up working on a project which defeated Bear

What build system was this using? (If you can share?)

**Comment by varungandhi-src** [comment]
I've opened another follow-up PR (https://github.com/sourcegraph/scip-clang/pull/387), thanks for the various links in your project README.

**Pull request merged**
